
postgres:
  prod:
    host: 'postgres-db-service'
    database: 'framework'
    user: 'admin'
    password: 'admin'
    port: '5432'
    active: True
  desa:
    host: 'localhost'
    database: 'framework'
    user: 'airflow'
    password: 'airflow'
    port: '5432'
    active: False

constantes:
  timeZone: 'America/Lima'